[package.create.set]
# The image reference to use for the Zarf agent, defaults to a locally built image
# renovate: depName=defenseunicorns/zarf
agent_image_tag = 'v0.32.1'
agent_image_domain = 'registry1.dso.mil/'
agent_image = 'ironbank/opensource/defenseunicorns/zarf/zarf-agent'

# Tag for the zarf injector binary to use
injector_version = '2023-08-02'
injector_amd64_shasum = '91de0768855ee2606a4f85a92bb480ff3a14ca205fd8d05eb397c18e15aa0247'
injector_arm64_shasum = '663df681deea957b0ec53538eab221691a83de8e95d86b8a29008af711934bee'

# The image reference to use for the registry that Zarf deploys into the cluster
# renovate: depName=distribution/distribution
registry_image_tag = '2.8.3'
registry_image_domain = 'registry1.dso.mil/'
registry_image = 'ironbank/opensource/docker/registry-v2'

# The image reference to use for the optional git-server Zarf deploys
# renovate: depName=go-gitea/gitea
gitea_server_version = '1.21.4'
gitea_image = 'registry1.dso.mil/ironbank/opensource/go-gitea/gitea'
